stevengj/GeometryPrimitives.jl

- src/GeometryPrimitives.jl
- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/kdtree.jl
- src/sphere.jl
- test/runtests.jl
This PR eliminates various deprecation warnings in Julia v0.6 while keeping it compatible with v0.5.
Change summary:
- Use dot syntax for `min`, `max`, `sqrt`, etc
- `sumabs2` → `sum(abs2, ...)`
- `abstract TypeName` → `@compat abstract type TypeName end`
- The v0.6 inner constructor syntax cannot be used even with the `Compat` package (see [here](https://github.com/JuliaLang/Compat.jl/issues/332#issuecomment-285864357)), so use the workaround suggested [here](https://github.com/JuliaLang/Compat.jl/issues/356#issuecomment-300836126).
> Eliminate deprecation warnings in Julia v0.6

- src/box.jl
- src/ellipsoid.jl
- test/runtests.jl
This PR corrects a small bug in the projection matrices in the outer constructors of `Box` and `Ellipsoid`.  
A few other improvements:
- Use the type-stable version of `maximum` on `SMatrix` (https://github.com/JuliaArrays/StaticArrays.jl/pull/86).
- Implement the precise `bounds` for rotated `Ellipsoid`.
> Fix projection matrix in Box and Ellipsoid, and implement precise bounds for Ellipsoid

- README.md
- appveyor.yml
- src/GeometryPrimitives.jl
- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/kdtree.jl
- src/sphere.jl
- test/runtests.jl
This PR changes the abstract type name `Object`, which is a bit too generic, to `Shape`.
> Change the name of the abstract type `Object` to `Shape`

- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/kdtree.jl
- src/sphere.jl
- test/runtests.jl
This PR make all the types defined in this module immutable, in order to 
- prevent the users from changing the fields of the instances, and
- make comparison between `Shape` instances easier (e.g., `Box([0,0],[1,1]) == Box([0,0],[1,1])` works after this change).
> Define == and hash for shape types

- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/sphere.jl
- test/runtests.jl
This PR eliminates instability of `bounds` and `normal` functions, by adding the extra type parameter `L` to the types `Box` and `Ellipsoid`.  This extra type parameter `L` is used to make the field `p` (projection matrix) of `Box` and `Ellipsoid` concrete, by changing its type from the abstract `SMatrix{N,N,Float64}` to the concrete `SMatrix{N,N,Float64,L}`.
Additionally, this PR surrounds tested functions by `@inferred` macro in `runtests.jl` to make sure all the functions are type-stable.
> Eliminate instability of bounds and normal

- .travis.yml
- REQUIRE
- appveyor.yml
- src/GeometryPrimitives.jl
- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/kdtree.jl
- src/sphere.jl
- test/runtests.jl
This PR drop the support for Julia 0.5, and use Julia 0.6 syntax (e.g., `struct` and `where {...}`) repository-wide.
> Drop support for Julia 0.5, and use Julia 0.6 syntax

- .travis.yml
- REQUIRE
- appveyor.yml
- src/GeometryPrimitives.jl
- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/kdtree.jl
- src/sphere.jl
- src/vxlcut.jl
- test/runtests.jl
This PR adds capability to calculate the volume fraction of the sub-volume of a voxel cut by a plane.  (The main function is `volfrac` in `src/vxlcut.jl`.)
The PR also adds detailed unit tests.
> Add vxlcut.jl for volume fraction of voxel cut by plane

- src/GeometryPrimitives.jl
- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/sphere.jl
This PR adds an additional type parameter `D` to `Shape`, and makes all the concrete shape types inherit from `Shape{N,D}`.
> Make all concrete shapes inherit from Shape{N,D}

- src/cylinder.jl
- src/ellipsoid.jl
- test/runtests.jl
This PR changes `Ellipsoid` constructors to take semiaxes instead of full axes.
Additionally, this PR adds a capability to construct an `Ellipsoid` out of a `Box` that describes the bounding box of the `Ellipsoid` to construct.
> Make Ellipsoid constructors to take semiaxes rather than full axes (closes #10)

- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/sphere.jl
This PR makes minor cosmetic changes: 
- commenting on inner constructors, and 
- changing the order of fields inside `==` and `hash` for `Cylinder` to match their order of declaration in `Cylinder`.
> Minor cosmetic changes

- src/box.jl
- test/runtests.jl
This PR makes `normal` for `Box` to return a unit vector even if the `Box` is non-rectangular (meaning that its axes are non-orthogonal).
> Make normal(...) return unit vector for non-rectangular Box

- src/box.jl
- test/runtests.jl
This PR fixes the error in `bounds` for `Box` such that it calculates the correct bounds even if the box is skewed.
> Calculate correct bounds for skewed Box

- src/GeometryPrimitives.jl
- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/sphere.jl
- test/runtests.jl
This PR adds the `surfpt_nearby` function, which returns a surface point nearby a given point and the outward normal at the surface point.
A few more details:
- `normal` is now implemented using `surfpt_nearby`.  This is because the calculation of the nearby surface point almost always requires the calculation of the outward normal direction.  Therefore, if one would like to calculate both the nearby surface point and outward normal, s/he is recommended to call `surfpt_nearby` once, instead of subsequently calling `normal`.
- `Cylinder` now calculates the outward normal differently than before.  Previously it returned the axis directions only if the point of evaluation is above the top base or below the bottom base.  (In other words, it didn't return the axis directions if the point is …
> Add surfpt_nearby that returns nearby surface point

- src/GeometryPrimitives.jl
- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/kdtree.jl
- src/sphere.jl
- test/runtests.jl
This PR fixes the type instability of `surfpt_nearby` discussed in #19, which was caused by the lack of the type parameter `L` in defining `Shape`.
This PR also changes the types of the fields `left` and `right` of `KDTree` to `KDTree{K,S}` so that the type `S` of the shapes constituting the k-d tree is correctly transmitted to the left and right branch of the tree.  Without this, the type of the output `Shape` of `findin(p::SVector{K}, kd::KDTree{K})` is not inferred sufficiently stably, notably lacking the type parameter `L` and leading to the instability of `surfpt_nearby` called on a `Shape` returned by `findin`.
Lastly, this PR changes `runtests.jl` such that the stabilities of `Shape` functions are tested collectively in a separate `testset`.
> Remove instability associated with {box,ellipsoid}.jl/surfpt_nearby and kdtree.jl/findin (fixes #19)

- .travis.yml
- appveyor.yml
- src/kdtree.jl
- test/runtests.jl
This PR fixes #21 by giving up branching in `KDTree` construction when either one of the left and right child trees has a similar number of shapes as the parent tree.
This PR also adds a test case where infinite recursion could happen in the original code.
> Prevent infinite recursion in KDTree construction (fixes #21)

- src/GeometryPrimitives.jl
This PR concerns type instability mentioned in #19.  Through the discussions in a Julia issue and discourse, it turned out that the best way to avoid this type instability is to use type assertion.  This PR adds comments that point the users to the relevant discussions and recommend using type assertion on the return values.
> Add comments on nontrivial type instability

- src/box.jl
- src/cylinder.jl
- test/runtests.jl
With this PR, the normal directions produced by `surpt_nearby` are more symmetric around sharpf corners of `Box` and `Cylinder`.  For example, for a unit square around the origin (with corners at `[±0.5, ±0.5]`), the normal direction obtained at `[0.51, 0.51]` is in the `[1, 1]` direction, whereas the normal direction obtained at `[-0.51, 0.51]` is in the `[-1, 1]` direction.  Previously this was not necessarily the case.
This change helps generating a symmetric material parameter distribution after subpixel smoothing of electromagnetic properties on a finite-difference grid.
> Take symmetry more seriously in surfpt_nearby around sharp corners

- src/box.jl
- src/ellipsoid.jl
- test/runtests.jl
This PR makes a few improvements on the usage of `StaticArrays`:
- Halve the size of `signmatrix` to work around `StaticArrays` [Issue #384](https://github.com/JuliaArrays/StaticArrays.jl/issues/384).
- Simplify some expressions by taking advantage of `StaticArrays` [PR #274](https://github.com/JuliaArrays/StaticArrays.jl/pull/274) on `broadcast`.
> Improve StaticArrays usage

- src/cylinder.jl
Some unnecessary dot operators between scalars in `src/cylinder.jl` were not removed in #23.  This PR replace them with regular operators.
> Further replace dot operators between scalars

- src/ellipsoid.jl
Extending the efforts in https://github.com/stevengj/GeometryPrimitives.jl/pull/27, eliminate unnecessary transpose operations on `SVector`s after https://github.com/JuliaArrays/StaticArrays.jl/pull/274.
> Further simplify StaticArrays usage

- src/GeometryPrimitives.jl
- src/box.jl
- src/cylinder.jl
- src/ellipsoid.jl
- src/periodize.jl
- src/sphere.jl
- test/runtests.jl
This PR adds `periodize` that generates a periodic array of a given shape.  It takes three arguments:
- `shp`: `Shape` to periodize
- `A`: matrix whose columns are lattice primitive vectors
- `∆range`: `Shape` specifying the range of lattice points
> Add a function to generate a periodic array of Shape

- .travis.yml
- REQUIRE
- appveyor.yml
- src/GeometryPrimitives.jl
- src/box.jl
- src/ellipsoid.jl
- src/kdtree.jl
- src/periodize.jl
- src/sphere.jl
- src/vxlcut.jl
- test/runtests.jl
This PR closes #31 by making various changes to make the package work for Julia 0.7.
The biggest change is to follow the new conventions for the `find*` functions.  There was `findin` in `kdtree.jl` to find a shape in `KDTree` containing a given point, but `Base.findin` is deprecated in 0.7 and the use of `findall(in(kdtree), point)` is  recommended instead.  If we implement `in(::KDTree)` for this usage, we also need to implement `enumerate(::KDTree)` because `findall` needs a mechanism to get a linear index of the found shape in `KDTree`.  Because `KDTree` is meant to store shapes in a tree structure rather than a linear list, implementing `enumerate(::KDTree)` is awkward.
Moreover, the original `findin` for `KDTree` did not return all the shapes containing a given point, but only one …
> Various updates for Julia 0.7

- Project.toml
- src/GeometryPrimitives.jl
- src/hyper/ball.jl
- src/hyper/cuboid.jl
- src/hyper/ellipsoid.jl
- src/planar/cross_section.jl
- src/planar/polygon.jl
- src/planar/sector.jl
- src/planar/special.jl
- src/prism/cylinder.jl
- src/prism/polygonal.jl
- src/prism/prism.jl
- src/prism/sectoral.jl
- src/util/kdtree.jl
- src/util/periodize.jl
- src/util/plotting.jl
- src/util/vxlcut.jl
- test/cylinder.jl
- test/kdtree.jl
- test/runtests.jl
- test/vxlcut.jl
@wsshin, I'm not really a fan of using AbbreviatedTypes here — I think it makes the code much harder to read for anyone who isn't you, since most of the Julia community does not use these abbreviations. 
This PR shouldn't affect any of your code using GeometryPrimitives, since the API is the same — the types are not changed, just spelled differently internally.
Closes #40.
> remove AbbreviatedTypes usage
